name: Build Electron App

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'  # Only run when files in the app folder are modified
  pull_request:
    branches:
      - master
    paths:
      - 'app/**'  # Trigger for pull requests on the app folder only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: app  # Specify the app directory
        run: |
          npm install

      - name: Build Electron app
        working-directory: app  # Specify the app directory
        run: |
          npm run dist

      - name: Check if dist directory exists
        id: check-dist
        run: |
          if [ -d "app/dist" ]; then
            echo "dist_exists=true" >> $GITHUB_ENV
          else
            echo "dist_exists=false" >> $GITHUB_ENV
          fi

      - name: Upload Build Artifacts
        if: env.dist_exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: electron-market-build
          path: app/dist/