name: Build and Release

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'  # Trigger on changes within the app directory. .
      - '.github/workflows/**'  # Trigger on changes within the workflows directory
  pull_request:
    branches:
      - master
    paths:
      - 'app/**'  # Trigger on pull requests affecting the app directory
      - '.github/workflows/**'  # Trigger on pull requests affecting the workflows directory

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Ensure you're using the latest version
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./app  # Specify the app directory
        run: |
          npm install

      - name: Build Electron app
        working-directory: ./app  # Specify the app directory
        run: |
          npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # Ensure you're using the latest version
        with:
          name: electron-market-build-${{ github.run_id }}-${{ github.run_number }}
          path: ./app/dist/

  create_release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/dist/*.zip
          asset_name: ElectronMarket-${{ matrix.os }}.zip
          asset_content_type: application/zip