name: Build Electron App

on:
  push:
    branches:
      - master
    paths:
      - 'app/**'  # Trigger on changes within the app directory
      - '.github/workflows/**'  # Trigger on changes within the workflows directory
  pull_request:
    branches:
      - master
    paths:
      - 'app/**'  # Trigger on pull requests affecting the app directory
      - '.github/workflows/**'  # Trigger on pull requests affecting the workflows directory

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Ensure you're using the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Ensure you're using the latest version
        with:
          node-version: '16'

      - name: Install dependencies
        working-directory: ./app  # Specify the app directory
        run: |
          npm install

      - name: Build Electron app
        working-directory: ./app  # Specify the app directory
        run: |
          npm run dist

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4  # Ensure you're using the latest version
        with:
          name: electron-market-build
          path: ./app/dist/
